application:
  port: 8001
  # Set the `APP_APPLICATION__HMAC_SECRET` environment variable
  # on Digital Ocean as well for production!
  hmac_secret: "long-and-very-secret-random-key-needed-to-verify-message-integrity"

database:
  port: 5432
  host: "127.0.0.1"
  username: "postgres"
  password: "password"
  database_name: "newsletter"

email_client:
  base_url: localhost
  timeout_milliseconds: 10000
  sender_email: test@gmail.com
  # We are only setting the development value,
  # we'll deal with the production token outside of version control
  # (given that it's a sensitive secret!)
  authorization_token: my-secret-token
